### ISSUE TITLE
NullReferenceExceptions causing slowdowns

### ISSUE THREAD

**Issue by KTVSUN** [microsoftenator2022/MiscTweaksAndFixes2#1]
My game gets super laggy when i install it.

Comes back to normal speed if i remove it.

**Comment by microsoftenator2022** [comment]
I can't replicate this. Please attach a copy of player.log

**Comment by KTVSUN** [comment]
My gamelog is 150 mb after a few minutes, full of errors because it s
trying
to access C:\Users\Aaron\source\repos\Wotr\MiscTweaksAndFixes2\MiscTweaksAndFixes\AddedContent\

Would this be the reason? Example:

[170.0487 - Default]: Object reference not set to an instance of an object
  at
MiscTweaksAndFixes.Tweaks.NaturalWeaponStacking.NaturalWeaponStacking.PatchConditions
(Kingmaker.EntitySystem.Entities.UnitEntityData unit) [0x00009] in
C:\Users\Aaron\source\repos\Wotr\MiscTweaksAndFixes2\MiscTweaksAndFixes\Tweaks\NaturalWeaponStacking.cs:304

  at
MiscTweaksAndFixes.Tweaks.NaturalWeaponStacking.NaturalWeaponStacking+ItemEntityWeapon_get_Size_Patch.Postfix
(Kingmaker.Enums.Size size, Kingmaker.Items.ItemEntityWeapon __instance)
[0x00014] in
C:\Users\Aaron\source\repos\Wotr\MiscTweaksAndFixes2\MiscTweaksAndFixes\Tweaks\NaturalWeaponStacking.cs:62

  at (wrapper dynamic-method)
Kingmaker.Items.ItemEntityWeapon.Kingmaker.Items.ItemEntityWeapon.get_Size_Patch1(Kingmaker.Items.ItemEntityWeapon)
  at Kingmaker.Items.ItemEntityWeapon.get_DamageDice () [0x00006] in
<9fbdaaba94e842ff9fe97bf4617a0789>:0
  at Kingmaker.Items.ItemEntityWeapon.IsBetterThan
(Kingmaker.Items.ItemEntityWeapon otherWeapon) [0x00000] in
<9fbdaaba94e842ff9fe97bf4617a0789>:0
  at Kingmaker.Items.UnitBody.SetEmptyHandWeapon
(Kingmaker.Blueprints.Items.Weapons.BlueprintItemWeapon weapon,
System.Boolean isMonkUnarmedStrike, System.Boolean isPermanent) [0x00072]
in <9fbdaaba94e842ff9fe97bf4617a0789>:0
  at Kingmaker.Designers.Mechanics.Buffs.EmptyHandWeaponOverride.SetWeapon
() [0x00017] in <9fbdaaba94e842ff9fe97bf4617a0789>:0
  at Kingmaker.Designers.Mechanics.Buffs.EmptyHandWeaponOverride.OnTurnOn
() [0x00006] in <9fbdaaba94e842ff9fe97bf4617a0789>:0
  at
Kingmaker.EntitySystem.EntityFactComponentDelegate`2+ComponentRuntime[TEntity,TData].OnTurnOn
() [0x0000d] in <9fbdaaba94e842ff9fe97bf4617a0789>:0

**Comment by microsoftenator2022** [comment]
That is helpful but I need the logs before this (from game start up onwards) to identify the root cause.

**Comment by microsoftenator2022** [comment]
You can upload your log here https://docs.google.com/forms/d/e/1FAIpQLSei1Cnpre7LhEKpEU176aCe_S8wxfE2dafGj0ZU17rm9YlVwQ/viewform

**Comment by KTVSUN** [comment]
I sent you player log and game log.

Cheers

**Comment by microsoftenator2022** [comment]
You don't appear to be using the current version of this mod (2.0.0.2) + there are a lot of errors from other mods that are causing issues eg. CustomNPCPortraits and FinneanTweaks

Deactivate all other mods, install [this debug version](https://github.com/microsoftenator2022/MiscTweaksAndFixes2/releases/download/2.0.0.2-debug%231/MiscTweaksAndFixes2.0.0.2-debug.zip), start the game at least once, and then upload your logs again

**Comment by KTVSUN** [comment]
Done, hope it helps.

**Comment by microsoftenator2022** [comment]
Thanks. That narrows it down a lot. There's a touch weapon (attack maybe?) without a wielder that is maybe triggering the issue but I don't know what it is or why it would be such an issue in your case specifically. I'll try to work around it in the next release (hopefully today) so please let me know if it's fixed.

**Comment by KTVSUN** [comment]
That last log i sent is just starting a new game, so there s only 1 default
character at level 1

**Comment by microsoftenator2022** [comment]
The logs indicate that's it's now catching and preventing the errors you mentioned earlier, so hopefully the issue doesn't reoccur.

**Comment by KTVSUN** [comment]
Beautiful, thank you
