### ISSUE TITLE
Mod does not appear in the ModMenu

### ISSUE THREAD

**Issue by edgedick** [microsoftenator2022/MiscTweaksAndFixes2#2]
As the title says, I can't get the mod to show up in the menu.  It shows as installed in the UMM window, both with and without any other mods, but I can't access this mod's options in ModMenu.

I am able to see other mods (Combat Relief), both with and without MiscTweaks installed, in ModMenu.

Any idea what could be causing this?

**Comment by microsoftenator2022** [comment]
Is this issue still present? I suggest deleting the mod folder and reinstalling

**Comment by edgedick** [comment]
It is still present.  I'd actually reinstalled the entire game, and then installed just MiscTweaks and ModMenu, and still it didn't show up.

**Comment by microsoftenator2022** [comment]
Can you attach a copy of Player.log and GameLogFull.txt?

**Comment by Niete314** [comment]
I have the same issue; every time I launch WoTR, I get an error message from Unity Mod Manager regarding MiscTweaksAndFixes2 (logs attached).
[GameLogFull.txt](https://github.com/microsoftenator2022/MiscTweaksAndFixes2/files/11684802/GameLogFull.txt)
[Player.log](https://github.com/microsoftenator2022/MiscTweaksAndFixes2/files/11684805/Player.log)

**Comment by microsoftenator2022** [comment]
Seems like you're missing the owlcat mod directory. Which is fine, just not a case I'd considered. For now, you can try creating an empty directory at `C:\Users\kkrau\AppData\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous\Modifications` but I'll push a fix out soon

**Comment by Niete314** [comment]
Thx.
